"""ISO 14229 service identifiers and common constants."""

SID_DIAGNOSTIC_SESSION_CONTROL = 0x10
SID_ECU_RESET = 0x11
SID_READ_DATA_BY_IDENTIFIER = 0x22
SID_READ_MEMORY_BY_ADDRESS = 0x23
SID_SECURITY_ACCESS = 0x27
SID_WRITE_DATA_BY_IDENTIFIER = 0x2E
SID_ROUTINE_CONTROL = 0x31
SID_TESTER_PRESENT = 0x3E
SID_NEGATIVE_RESPONSE = 0x7F

SESSION_DEFAULT = 0x01
SESSION_PROGRAMMING = 0x02
SESSION_EXTENDED = 0x03

ROUTINE_CONTROL_START = 0x01
ROUTINE_CONTROL_STOP = 0x02
ROUTINE_CONTROL_REQUEST_RESULTS = 0x03
